version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Canada/Pacific'
      # WEBPASSWORD: '<SOME_SECRET_PASSWORD>'
      VIRTUAL_HOST: 'pi-hole.local'
      VIRTUAL_PORT: '80'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped