version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080
      - 50000:50000
    environment:
      TZ: 'Canada/Pacific'
      VIRTUAL_HOST: 'jenkins.local'
      VIRTUAL_PORT: '8080'
    container_name: jenkins-lts
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    restart: unless-stopped