apiVersion: v1
kind: Service
metadata:
  labels:
    app: learn
  name: learn
  namespace: dev
spec:
  ports:
  - name: '8000'
    port: 8000
    targetPort: 8000
  selector:
    app: learn
status:
  loadBalancer: {}
